workflows:
  android-app:
    name: Build Android APK
    max_build_duration: 10
    environment:
      java: 17
    scripts:
      - name: Prepare Wrapper (generate on runner)
        script: |
          if ! command -v gradle >/dev/null 2>&1; then
            echo "Gradle not found on image"; exit 1
          fi
          rm -rf gradle/wrapper gradlew
          gradle wrapper --gradle-version 8.1.1
          chmod +x gradlew
          echo "Wrapper dir listing:" && ls -lah gradle/wrapper
          echo "Check classes in wrapper JAR:" && jar tf gradle/wrapper/gradle-wrapper.jar | head -n 20
      - name: Build APK
        script: |
          ./gradlew --version
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
