workflows:
  android-app:
    name: Build Android APK
    max_build_duration: 10
    environment:
      java: 17
    scripts:
      - name: Prepare Gradle locally (bootstrap)
        script: |
          set -e
          echo "Downloading Gradle 8.1.1..."
          curl -fL -o gradle.zip https://services.gradle.org/distributions/gradle-8.1.1-bin.zip
          unzip -q gradle.zip
          export GRADLE_HOME="$PWD/gradle-8.1.1"
          echo "Generating wrapper with local Gradle..."
          "$GRADLE_HOME/bin/gradle" wrapper --gradle-version 8.1.1
          chmod +x gradlew
          echo "Check wrapper JAR has WrapperMain:"
          jar tf gradle/wrapper/gradle-wrapper.jar | grep "org/gradle/wrapper/GradleWrapperMain.class"
      - name: Build APK
        script: |
          ./gradlew --version
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk