workflows:
  android-app:
    name: Build Android APK
    max_build_duration: 10
    environment:
      android_signing:
        keystore_reference: "default_keystore"
      vars:
        PACKAGE_NAME: "com.example.teekeytest"
      java: 17
    scripts:
      - name: Build APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
